name: clippyme

networks:
  clippyme-net:
    driver: bridge

services:
  backend:
    build: .
    container_name: clippyme-backend
    image: clippyme-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./data:/app/data
    networks:
      - clippyme-net
    restart: unless-stopped

  frontend:
    build: ./dashboard
    container_name: clippyme-frontend
    image: clippyme-frontend
    ports:
      - "5175:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    networks:
      - clippyme-net
    restart: unless-stopped
    depends_on:
      - backend
